apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-cdi-sis
  labels:
    app: k8s-cdi-sis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-cdi-sis
  template:
    metadata:
      labels:
        app: k8s-cdi-sis
    spec:
      containers:
        - name: k8s-cdi-sis
          image: icsdev/cdi-sis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: JPDA_ADDRESS
              value: "8000"
          volumeMounts:
            # --- Security Certs/Config Mounts ---
            # NOTE: Update the 'hostPath.path' values to match your local system paths where ${CHEF_DIR}, etc., resolve to.
            - name: root-truststore
              mountPath: /etc/ssl/infaca/truststore.jks
              subPath: truststore.jks
            - name: root-ca-bundle
              mountPath: /etc/ssl/infaca/ca-bundle.pem
              subPath: ca-bundle.pem
            - name: cdi-sis-keystore
              mountPath: /etc/ssl/infaca/keystore.jks
              subPath: cdi-sis-keystore.jks
            - name: cdi-sis-bundle
              mountPath: /etc/ssl/infaca/cdi-sis-bundle.pem
              subPath: cdi-sis-bundle.pem
            - name: cdi-sis-key
              mountPath: /etc/ssl/infaca/cdi-sis-key.pem
              subPath: cdi-sis-key.pem
      volumes:
        # Volume definitions for hostPath mounts
        - name: root-truststore
          hostPath:
            path: /data/icsdevuser/p4ws/icsdev/security/root/root-truststore.jks
            type: File
        - name: root-ca-bundle
          hostPath:
            path: /data/icsdevuser/p4ws/icsdev/security/root/root-ca-bundle.pem
            type: File
        - name: cdi-sis-keystore
          hostPath:
            path: /data/icsdevuser/p4ws/icsdev/security/certs/cdi-sis/cdi-sis-keystore.jks
            type: File
        - name: cdi-sis-keystore
          hostPath:
            path: /data/icsdevuser/p4ws/icsdev/security/certs/cdi-sis/cdi-sis-keystore.jks
            type: File
        - name: cdi-sis-keystore
          hostPath:
            path: /data/icsdevuser/p4ws/icsdev/security/certs/cdi-sis/cdi-sis-keystore.jks
            type: File
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-cdi-sis-service
spec:
  type: LoadBalancer
  selector:
    app: k8s-cdi-sis
  ports:
    - protocol: "TCP"
      port: 16180
      targetPort: 16180
      nodePort: 30000